version: "3.9"
services:
  php-apache:
    ports:
      - "8082:80"
    build: './.docker/php'
    volumes:
      - ./app:/var/www/html
    networks:
      - dev-env
volumes:
  app:
networks:
  dev-env:
